Added VScode workspace setting
macrobomastercontrolteam/MacRM_Standard_2022 pull request #6
Opened 2022-10-26 23:47 UTC by GJSK-Novice

2022-10-26 23:51 UTC, mac-robomaster requested changes
Left some QA messages, @GJSK-Novice please take a look

2022-10-26 23:51 UTC, mac-robomaster commented on .vscode/standard_robot.code-workspace
> +		{
QA message 1

2022-10-26 23:53 UTC, GJSK-Novice commented on .vscode/standard_robot.code-workspace
> +		{
Commit 1817882d7b1899fe13efba1c1d140c116af940f0

2022-10-26 23:55 UTC, mac-robomaster approved these changes
Approved

2022-10-27 00:01 UTC, mac-robomaster approved these changes
Approved

2022-10-27 00:02 UTC, merged